
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "../components/SideNav";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <React.Suspense fallback={<div>Loading...</div>}>
          <div className="min-h-full bg-white w-full">
            <Header />
            <div className="flex h-full w-full md:overflow-x-hidden">
              <SideNav />
              {children}
            </div>
          </div>
        </React.Suspense>
      </body>
    </html>
  );
}
